# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApacheLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_dateTime', models.DateTimeField()),
                ('http_method', models.CharField(max_length=10)),
                ('http_response', models.CharField(max_length=10)),
                ('response_time', models.TimeField()),
                ('url', models.CharField(max_length=300)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
    ]
