# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApacheLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.IntegerField()),
                ('status', models.IntegerField()),
                ('request_first_line', models.CharField(max_length=500, null=True)),
                ('response_bytes_clf', models.CharField(max_length=30, null=True)),
                ('remote_host', models.CharField(max_length=500, null=True)),
                ('request_http_ver', models.CharField(max_length=500, null=True)),
                ('request_url_port', models.CharField(max_length=5, null=True)),
                ('remote_logname', models.CharField(max_length=30, null=True)),
                ('request_method', models.CharField(max_length=4, null=True)),
                ('time_received', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
