# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        ('log_formats', '0001_initial'),
        ('apache_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apachelog',
            unique_together=set([('site', 'log_format', 'remote_host', 'request_method', 'status', 'request_url', 'time_received_utc_isoformat')]),
        ),
    ]
