# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apache_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apachelog',
            name='response_bytes',
            field=models.DecimalField(decimal_places=6, max_digits=60, null=True),
        ),
        migrations.AlterField(
            model_name='apachelog',
            name='time_millisecond',
            field=models.DecimalField(decimal_places=6, max_digits=60, null=True),
        ),
        migrations.AlterField(
            model_name='apachelog',
            name='time_second',
            field=models.DecimalField(decimal_places=6, max_digits=60, null=True),
        ),
    ]
