# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apache_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apachelog',
            old_name='site_id',
            new_name='format_id',
        ),
    ]
