# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apache_logs', '0002_auto_20161113_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apachelog',
            old_name='request_first_line',
            new_name='request_url',
        ),
        migrations.RemoveField(
            model_name='apachelog',
            name='remote_logname',
        ),
        migrations.RemoveField(
            model_name='apachelog',
            name='request_url_port',
        ),
        migrations.RemoveField(
            model_name='apachelog',
            name='time_received',
        ),
        migrations.AddField(
            model_name='apachelog',
            name='local_ip',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='apachelog',
            name='request_url_path',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='apachelog',
            name='time_received_tz_isoformat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apachelog',
            name='remote_host',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apachelog',
            name='request_http_ver',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
