# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apache_logs', '0003_auto_20161113_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apachelog',
            name='request_http_ver',
        ),
        migrations.RemoveField(
            model_name='apachelog',
            name='request_url',
        ),
    ]
